# == ZSH SETTINGS ==

# -- Bindings --
bindkey -e # emacs mode line editting
bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line
bindkey '\e[3~' delete-char

# -- History --
export HISTFILE=$HOME/.environments/osx/zsh/history
export HISTSIZE=10000
export SAVEHIST=10000

setopt extendedglob # enables more complex "extended glob" (needed to make colours work in auto-completion)

# -- Completions --
setopt AUTO_LIST
setopt AUTO_MENU
setopt MENU_COMPLETE

WORDCHARS='*?_-[]~=&;!#$%^(){}<>' # chars as part of filename

autoload -U compinit && compinit # enables extra auto-completion

zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path $HOME/.environments/osx/zsh/cache
zstyle ':completion:*:cd:*' ignore-parents parent pwd
zstyle ':completion:*:match:*' original only
zstyle ':completion::prefix-1:*' completer _complete
zstyle ':completion:predict:*' completer _complete
zstyle ':completion:incremental:*' completer _complete _correct
zstyle ':completion:*' completer _complete _prefix _correct _prefix _match _approximate
zstyle ':completion:*' expand true
zstyle ':completion:*' squeeze-shlashes true
zstyle ':completion::complete:*' '\\'
zstyle ':completion:*:*:*:default' menu yes select
zstyle ':completion:*:*:default' force-list always
zmodload  zsh/complist
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'

zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric

compdef pkill=kill
compdef pkill=killall
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:processes' command 'ps -au$USER'

zstyle ':completion:*:matches' group 'yes'
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:options' auto-description '%d'
zstyle ':completion:*:descriptions' format $'\e[01;33m -- %d --\e[0m'
zstyle ':completion:*:messages' format $'\e[01;35m -- %d --\e[0m'
zstyle ':completion:*:warnings' format $'\e[01;31m -- No Matches Found --\e[0m'

# -- Aliases --
alias ls='ls -G'
alias ll='ls -alh'
alias mkdir='mkdir -p'
alias cp='cp -R'
alias chown='chown -R'
alias chmod='chmod -R'
alias pp='cd ~/Projects'
alias grep='grep --color'
alias vm='VBoxManage'
alias rspec='rspec --color --format documentation'
alias e='subl -n'
alias vim='mvim -v'
alias df='df -h'
alias du='du -sh'
alias import=python_import
alias cls='clear'
alias gradle='gradle --daemon'
alias less='less -FXR'

# read-line wraps
alias clj='rlwrap clj'
alias fansh='rlwrap fansh'
alias sqlplus='rlwrap sqlplus'

# -- Variables --
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home
export GROOVY_HOME=/usr/local/Cellar/groovy/2.0.0/libexec
export EDITOR="subl -w"
export VISUAL="subl -w"

# -- Some Mountain Lion shit --
export CFLAGS="-I/opt/X11/include"

# -- Proxy Settings --
function enable_proxy() {
   export http_proxy="http://qaproxy.gid.gap.com:8080/"
   export https_proxy="http://qaproxy.gid.gap.com:8080/"
   export ftp_proxy="http://qaproxy.gid.gap.com:8080/"
   export no_proxy="localhost,.gap.com,.gap.dev,127.0.0.0/8,10.0.0.0/8,192.168.0.0/16"
}

function disable_proxy() {
   export http_proxy=""
   export https_proxy=""
   export ftp_proxy=""
   export no_proxy=""
}

function p() { cd ~/Projects/$1;  }
function _p() { _files -W ~/Projects -/; }
compdef _p p

export PATH=$HOME/.environments/osx/bin:/usr/local/sbin:/usr/local/bin:/usr/local/share/npm/bin:/usr/local/share/python:$JAVA_HOME/bin:/usr/local/Cellar/tomcat/6.0.26/bin:$PATH
. "$HOME/.rvm/scripts/rvm"
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

source $HOME/.environments/osx/zsh/isa.theme
source $HOME/.environments/osx/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
